# run: conda env create --file environment.yml
name: hpc
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
- python>=3.8
- jupyter>=1.0.0
- numpy>=1.10.1
- matplotlib>=1.4.3
- pandas>=0.17.1
- requests>=2.7.0
- scikit-learn
- numba
- salib
- mpi4py
- bs4
- tqdm
- pycuda
- Pillow
# - pip
# - pip:
#   - smth

  # works for regular pip packages
  # - docx
  # - gooey
  # - matplotlib==2.0.0  # pin version for pip
  # # and for wheels
  # - http://www.lfd.uci.edu/~gohlke/pythonlibs/bofhrmxk/opencv_python-3.1.0-cp35-none-win_amd64.whl